/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package twitter.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Coordinate extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -9122590354118758917L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Coordinate\",\"namespace\":\"twitter.avro\",\"fields\":[{\"name\":\"long\",\"type\":[\"double\",\"null\"],\"default\":0},{\"name\":\"lat\",\"type\":[\"double\",\"null\"],\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.Double long$;
  @Deprecated public java.lang.Double lat;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Coordinate() {}

  /**
   * All-args constructor.
   */
  public Coordinate(java.lang.Double long$, java.lang.Double lat) {
    this.long$ = long$;
    this.lat = lat;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return long$;
    case 1: return lat;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: long$ = (java.lang.Double)value$; break;
    case 1: lat = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'long$' field.
   */
  public java.lang.Double getLong$() {
    return long$;
  }

  /**
   * Sets the value of the 'long$' field.
   * @param value the value to set.
   */
  public void setLong$(java.lang.Double value) {
    this.long$ = value;
  }

  /**
   * Gets the value of the 'lat' field.
   */
  public java.lang.Double getLat() {
    return lat;
  }

  /**
   * Sets the value of the 'lat' field.
   * @param value the value to set.
   */
  public void setLat(java.lang.Double value) {
    this.lat = value;
  }

  /**
   * Creates a new Coordinate RecordBuilder.
   * @return A new Coordinate RecordBuilder
   */
  public static twitter.avro.Coordinate.Builder newBuilder() {
    return new twitter.avro.Coordinate.Builder();
  }
  
  /**
   * Creates a new Coordinate RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Coordinate RecordBuilder
   */
  public static twitter.avro.Coordinate.Builder newBuilder(twitter.avro.Coordinate.Builder other) {
    return new twitter.avro.Coordinate.Builder(other);
  }
  
  /**
   * Creates a new Coordinate RecordBuilder by copying an existing Coordinate instance.
   * @param other The existing instance to copy.
   * @return A new Coordinate RecordBuilder
   */
  public static twitter.avro.Coordinate.Builder newBuilder(twitter.avro.Coordinate other) {
    return new twitter.avro.Coordinate.Builder(other);
  }
  
  /**
   * RecordBuilder for Coordinate instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Coordinate>
    implements org.apache.avro.data.RecordBuilder<Coordinate> {

    private java.lang.Double long$;
    private java.lang.Double lat;

    /** Creates a new Builder */
    private Builder() {
      super(twitter.avro.Coordinate.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(twitter.avro.Coordinate.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.long$)) {
        this.long$ = data().deepCopy(fields()[0].schema(), other.long$);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lat)) {
        this.lat = data().deepCopy(fields()[1].schema(), other.lat);
        fieldSetFlags()[1] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing Coordinate instance
     * @param other The existing instance to copy.
     */
    private Builder(twitter.avro.Coordinate other) {
            super(twitter.avro.Coordinate.SCHEMA$);
      if (isValidValue(fields()[0], other.long$)) {
        this.long$ = data().deepCopy(fields()[0].schema(), other.long$);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lat)) {
        this.lat = data().deepCopy(fields()[1].schema(), other.lat);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'long$' field.
      * @return The value.
      */
    public java.lang.Double getLong$() {
      return long$;
    }

    /**
      * Sets the value of the 'long$' field.
      * @param value The value of 'long$'.
      * @return This builder.
      */
    public twitter.avro.Coordinate.Builder setLong$(java.lang.Double value) {
      validate(fields()[0], value);
      this.long$ = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'long$' field has been set.
      * @return True if the 'long$' field has been set, false otherwise.
      */
    public boolean hasLong$() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'long$' field.
      * @return This builder.
      */
    public twitter.avro.Coordinate.Builder clearLong$() {
      long$ = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'lat' field.
      * @return The value.
      */
    public java.lang.Double getLat() {
      return lat;
    }

    /**
      * Sets the value of the 'lat' field.
      * @param value The value of 'lat'.
      * @return This builder.
      */
    public twitter.avro.Coordinate.Builder setLat(java.lang.Double value) {
      validate(fields()[1], value);
      this.lat = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'lat' field has been set.
      * @return True if the 'lat' field has been set, false otherwise.
      */
    public boolean hasLat() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'lat' field.
      * @return This builder.
      */
    public twitter.avro.Coordinate.Builder clearLat() {
      lat = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Coordinate build() {
      try {
        Coordinate record = new Coordinate();
        record.long$ = fieldSetFlags()[0] ? this.long$ : (java.lang.Double) defaultValue(fields()[0]);
        record.lat = fieldSetFlags()[1] ? this.lat : (java.lang.Double) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
